[book]
autors = ["The Cardano Authors"]
language = "en"
multilingual = false
src = "docs"
title = "The Cardano Operations Book"

[build]
build-dir = "docs/book"

[output.html]
edit-url-template = "https://github.com/input-output-hk/cardano-world/edit/master/src/{path}"
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/input-output-hk/cardano-world"

[preprocessor.kroki-preprocessor]
command = "mdbook-kroki-preprocessor"
