[book]
autors = ["The Cardano Authors"]
title = "The Cardano Operations Book"

[output.html]
edit-url-template = "https://github.com/input-output-hk/cardano-world/edit/master/src/{path}"
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/input-output-hk/cardano-world"
