{
 "title": "Dbsync",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Dbsync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cardano Dbsync DB Block Height",
   "type": "graph",
   "description": "Shows dbsync's synchronized block height.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_db_sync_db_block_height{namespace=\"$namespace\"}",
     "legendFormat": "{{nomad_alloc_name}}"
    }
   ]
  },
  {
   "title": "Cardano Dbsync Node Block Height",
   "type": "graph",
   "description": "Shows the block height of node as known by dbsync.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_db_sync_node_block_height{namespace=\"$namespace\"}",
     "legendFormat": "{{nomad_alloc_name}}"
    }
   ]
  },
  {
   "title": "Cardano Dbsync DB Slot Height",
   "type": "graph",
   "description": "Shows dbsync's synchronized slot height.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_db_sync_db_slot_height{namespace=\"$namespace\"}",
     "legendFormat": "{{nomad_alloc_name}}"
    }
   ]
  },
  {
   "title": "Cardano Dbsync To Node Block Height Difference",
   "type": "graph",
   "description": "Shows the difference between dbsync and node's block height.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_db_sync_node_block_height{namespace=\"$namespace\"} - cardano_db_sync_db_block_height{namespace=\"$namespace\"}",
     "legendFormat": "{{nomad_alloc_name}}"
    }
   ]
  },
  {
   "title": "Cardano Dbsync DB Queue Length",
   "type": "graph",
   "description": "Shows dbsync's queue length.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_db_sync_db_queue_length{namespace=\"$namespace\"}",
     "legendFormat": "{{nomad_alloc_name}}"
    }
   ]
  }
 ]
}