{
 "title": "Faucet",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(faucet_utxo, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pools delegated to",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "faucet_delegation_pools{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delegations available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "faucet_delegation_available{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UTxO count per size (required by api key)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "faucet_utxo{namespace=~\"$namespace\",is_valid=\"1\"}",
     "legendFormat": "utxo count for size {{ada}} ada"
    },
    { "expr": "bucket_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UTxO count per size (not required)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "faucet_utxo{namespace=~\"$namespace\",is_valid!=\"1\"}",
     "legendFormat": "utxo count for size {{ada}} ada"
    },
    { "expr": "bucket_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rewards for each delegation (ADA)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "faucet_delegation_rewards{namespace=~\"$namespace\"} / 1E6",
     "legendFormat": "{{pool}}"
    }
   ]
  }
 ]
}