{
 "title": "Wireguard",
 "description": "Wireguard Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(wireguard_latest_handshake_seconds, namespace)"
    }
   },
   {
    "name": "alias",
    "query": {
     "query": "label_values(wireguard_latest_handshake_seconds, alias)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Peer Last Handshake",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time()-wireguard_latest_handshake_seconds{namespace=\"$namespace\", alias=\"$alias\"}",
     "legendFormat": "{{alias}}-{{public_key}}"
    }
   ]
  },
  {
   "title": "Peer Transmit Bytes Total (1m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(wireguard_sent_bytes_total{namespace=\"$namespace\", alias=\"$alias\"}[1m])",
     "legendFormat": "{{alias}}-{{public_key}}"
    }
   ]
  },
  {
   "title": "Peer Receive Bytes Total (1m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(wireguard_received_bytes_total{namespace=\"$namespace\", alias=\"$alias\"}[1m])",
     "legendFormat": "{{alias}}-{{public_key}}"
    }
   ]
  }
 ]
}