{
 "title": "Global Performance Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "function", "label": "Aggregator", "query": "avg" },
   { "name": "name_filter", "label": "Nodes", "query": { "query": "label_values(nomad_alloc_name)" } }
  ]
 },
 "panels": [
  {
   "title": "$function of nodes current \"residency\" (amount of live data)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "$function(rts_gc_current_bytes_used{nomad_alloc_name=~\"$name_filter\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "$function of block propagation delay (5 min sliding average)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$function(avg_over_time(cardano_node_metrics_blockfetchclient_blockdelay_s{nomad_alloc_name=~\"$name_filter\"}[5m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "$function of CPU Utilization (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "$function((irate((rts_gc_cpu_ms{nomad_alloc_name=~\"$name_filter\"} + rts_gc_mutator_cpu_ms{nomad_alloc_name=~\"$name_filter\"} + rts_gc_init_cpu_ms{nomad_alloc_name=~\"$name_filter\"})[1m]))/ 1000) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "$function of TCP connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$function(cardano_node_metrics_connectionManager_unidirectionalConns{nomad_alloc_name=~\"$name_filter\"} + cardano_node_metrics_connectionManager_duplexConns{nomad_alloc_name=~\"$name_filter\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Network usefulness factor (tm): ratio of blocks served in last hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "$function(rate(cardano_node_metrics_served_block_latest_count_int{nomad_alloc_name=~\"$name_filter\"}[1h])/rate(cardano_node_metrics_blockNum_int{nomad_alloc_name=~\"$name_filter\"}[1h])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}