creation_rules:
  # Dev
  - path_regex: cardano/shelley-qa/*
    hc_vault_transit_uri: "https://vault.world.dev.cardano.org/v1/sops/keys/dev"
  - path_regex: cardano/preprod/*
    hc_vault_transit_uri: "https://vault.world.dev.cardano.org/v1/sops/keys/dev"
  - path_regex: cardano/preview/*
    hc_vault_transit_uri: "https://vault.world.dev.cardano.org/v1/sops/keys/dev"
  - path_regex: cardano/sanchonet/*
    hc_vault_transit_uri: "https://vault.world.dev.cardano.org/v1/sops/keys/dev"
  - path_regex: cardano/private/*
    hc_vault_transit_uri: "https://vault.world.dev.cardano.org/v1/sops/keys/dev"
  # Ops
  - path_regex: patroni/infra*
    hc_vault_transit_uri: "https://vault.world.dev.cardano.org/v1/sops/keys/ops"
  - path_regex: metadata/infra*
    hc_vault_transit_uri: "https://vault.world.dev.cardano.org/v1/sops/keys/ops"
  - path_regex: db-sync/shelley-qa*
    hc_vault_transit_uri: "https://vault.world.dev.cardano.org/v1/sops/keys/ops"
  - path_regex: db-sync/preprod*
    hc_vault_transit_uri: "https://vault.world.dev.cardano.org/v1/sops/keys/ops"
  - path_regex: db-sync/preview*
    hc_vault_transit_uri: "https://vault.world.dev.cardano.org/v1/sops/keys/ops"
  - path_regex: db-sync/sanchonet*
    hc_vault_transit_uri: "https://vault.world.dev.cardano.org/v1/sops/keys/ops"
  - path_regex: db-sync/mainnet*
    hc_vault_transit_uri: "https://vault.world.dev.cardano.org/v1/sops/keys/ops"
  - path_regex: db-sync/private*
    hc_vault_transit_uri: "https://vault.world.dev.cardano.org/v1/sops/keys/ops"
  - path_regex: faucet/preprod*
    hc_vault_transit_uri: "https://vault.world.dev.cardano.org/v1/sops/keys/ops"
  - path_regex: faucet/preview*
    hc_vault_transit_uri: "https://vault.world.dev.cardano.org/v1/sops/keys/ops"
  - path_regex: faucet/sanchonet*
    hc_vault_transit_uri: "https://vault.world.dev.cardano.org/v1/sops/keys/ops"
  - path_regex: faucet/private*
    hc_vault_transit_uri: "https://vault.world.dev.cardano.org/v1/sops/keys/ops"
